# Auto-generated by Lumenary - Mock routes for testing
from fastapi import FastAPI
from api.models import *

app = FastAPI(title="Mock API for testing")

# Mock endpoints with pass statements
@app.post('/api/conversation_engine/start_chat_session')
async def conversation_engine_start_chat_session():
    pass

@app.post('/api/conversation_engine/send_chat_message')
async def conversation_engine_send_chat_message(body: BodyConversationEngineSendChatMessage):
    pass

@app.post('/api/conversation_engine/get_chat_history')
async def conversation_engine_get_chat_history(body: BodyConversationEngineGetChatHistory):
    pass

@app.post('/api/proposal_generator/generate_proposal')
async def proposal_generator_generate_proposal(body: BodyProposalGeneratorGenerateProposal):
    pass

@app.post('/api/proposal_generator/get_proposal_details')
async def proposal_generator_get_proposal_details(body: BodyProposalGeneratorGetProposalDetails):
    pass

@app.post('/api/google_drive_service/upload_proposal_to_drive')
async def google_drive_service_upload_proposal_to_drive(body: BodyGoogleDriveServiceUploadProposalToDrive):
    pass

@app.post('/api/google_drive_service/test_google_drive_connection')
async def google_drive_service_test_google_drive_connection():
    pass

@app.post('/api/calendar_service/get_calendar_booking_link')
async def calendar_service_get_calendar_booking_link(body: BodyCalendarServiceGetCalendarBookingLink):
    pass

@app.post('/api/calendar_service/mark_calendar_booking_completed')
async def calendar_service_mark_calendar_booking_completed(body: BodyCalendarServiceMarkCalendarBookingCompleted):
    pass